apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-conversion-server
spec:
  selector:
    matchLabels:
      app: epoch-conversion-server
  replicas: 4
  template:
    metadata:
      labels:
        app: epoch-conversion-server
    spec:
      containers:
      - name: epoch-conversion-server
        image: epoch-conversion-server
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---

kind: Service
apiVersion: v1
metadata:
  name: epoch-conversion-server-svc
spec:
  type: ClusterIP
  selector:
    app: epoch-conversion-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
